### ISSUE TITLE
Feature request: Improve blog navigation

### ISSUE THREAD

**Issue by deanoemcke** [RichardLitt/2117.91USD#8]
Navigating to the next blog entry is cumbersome. Especially now that you've reached the 10's.
You should include a link at the end of each entry to the next one.
And maybe a link to the first one from the README.

**Comment by RichardLitt** [comment]
Easiest way is probably to build a website for the blog. You think?

**Comment by RichardLitt** [comment]
I made a blog. This should be closed now. Feel free to open new issues for issues with the blog. https://richardlitt.github.io/2117.91USD/
